### ISSUE TITLE
SWYH makes my router crash

### ISSUE THREAD

**Issue by ghaspias** [StreamWhatYouHear/SWYH#1]
Having the honor of submitting the first issue, I tak the oportunity to congratulate Sebastien on this software and the decision to open-source it!

As the title says, every time I start SWYH, my router crashes every time in about a minute. I will try to check the logs from the router, and will update this with more details, but in the meanwhile I wonder if someone else has had this behaviour?

Happy contributing, everybody!

**Comment by mpratt14** [comment]
(Having the honor of responding to the first issue...spelling error (tak) lol)

Brand/Model of Router would help...

Also WiFi information maybe?

**Comment by sebastienwarin** [comment]
SWYH send SSTP packets on the network ! I think there is a bug in your router when receive this packets !
I can help you !
Sorry
