### ISSUE TITLE
Crashes when DLNA player is selected

### ISSUE THREAD

**Issue by sinancetinkaya** [StreamWhatYouHear/SWYH#11]
Video: https://drive.google.com/file/d/0B1PNkS9SaGXtcFJNMHdYRW9wcFU/view?usp=drivesdk
OS: Windows 7 64bit

Stacktrace:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> *************\* Exception Text **************
> OpenSource.UPnP.AV.CdsMetadata.Error_BadMetadata: Bad metadata. Expecting item or container element in MediaObject constructor.
>    at OpenSource.UPnP.AV.CdsMetadata.MediaObject.UpdateEverything_CheckElementName(XmlElement xmlElement, Boolean& isItem, Boolean& isContainer)
>    at OpenSource.UPnP.AV.CdsMetadata.MediaObject.UpdateEverything(Boolean updateResources, Boolean updateChildren, Type instantiateTheseForResources, Type instantiateTheseForChildItems, Type instantiateTheseForChildContainers, XmlElement xmlElement, ArrayList& proposedChildren)
>    at OpenSource.UPnP.AV.CdsMetadata.MediaItem.FinishInitFromXml(XmlElement xmlElement)
>    at OpenSource.UPnP.AV.CdsMetadata.MediaObject..ctor(XmlElement xmlElement)
>    at OpenSource.UPnP.AV.CdsMetadata.MediaItem..ctor(XmlElement xmlElement)
>    at SWYH.UPnP.DvContentDirectory.GetWasapiMediaItem()
>    at SWYH.App.streamMenu_RendererSelected(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> *************\* Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> 
> SWYH
>     Assembly Version: 1.4.0.0
>     Win32 Version: 1.4.16069.0
> ##     CodeBase: file:///D:/Program%20Files/Stream%20What%20You%20Hear/SWYH.exe
> 
> PresentationFramework
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
> 
> WindowsBase
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
> 
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> 
> PresentationCore
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
> 
> System.Xaml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
> 
> UPNPAV_RendererStack
>     Assembly Version: 1.0.5912.18019
>     Win32 Version: 1.0.5912.18019
> ##     CodeBase: file:///d:/Program%20Files/Stream%20What%20You%20Hear/UPNPAV_RendererStack.DLL
> 
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> 
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34270 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> 
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> 
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> 
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> 
> PresentationFramework.Classic
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.classic/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.classic.dll
> 
> UPnP
>     Assembly Version: 1.0.5912.18018
>     Win32 Version: 1.0.5912.18018
> ##     CodeBase: file:///d:/Program%20Files/Stream%20What%20You%20Hear/UPnP.DLL
> 
> UPNP_AV
>     Assembly Version: 1.0.5912.18019
>     Win32 Version: 1.0.5912.18019
> ##     CodeBase: file:///d:/Program%20Files/Stream%20What%20You%20Hear/UPNP_AV.DLL
> 
> NAudio
>     Assembly Version: 1.7.3.0
>     Win32 Version: 1.7.3.0
> ##     CodeBase: file:///d:/Program%20Files/Stream%20What%20You%20Hear/NAudio.DLL
> 
> NAudio.Lame
>     Assembly Version: 1.0.2.33669
>     Win32 Version: 1.0.2.33669
> ##     CodeBase: file:///d:/Program%20Files/Stream%20What%20You%20Hear/NAudio.Lame.DLL
> 
> LameDLLWrap
>     Assembly Version: 1.0.5071.33669
>     Win32 Version: 1.0.2.33669
> ##     CodeBase: file:///d:/Program%20Files/Stream%20What%20You%20Hear/NAudio.Lame.dll
> 
> UPNPAVCDSML
>     Assembly Version: 1.0.5912.18019
>     Win32 Version: 1.0.5912.18019
> ##     CodeBase: file:///d:/Program%20Files/Stream%20What%20You%20Hear/UPNPAVCDSML.DLL
> 
> System.Web
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.0.30319.34280 built by: FX452RTMGDR
> ##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
> 
> *************\* JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by sebastienwarin** [comment]
Fix in release 1.5
