### ISSUE TITLE
HTTP Live Streaming - Incorrect network selected

### ISSUE THREAD

**Issue by addshore** [StreamWhatYouHear/SWYH#21]
I just downloaded this and managed to get it working (and that is awesome) however when first starting the HTTP Live Streaming it seemed to bind to a single IP and port (not the one actually used in my house) in fact it was a Docker network.

It would be great to either:
 1 - Have some sort of prioritization, ie, LAN first then WLAN and then other networks
 2 - Allow selection of IP or network device to listen on
 3 - Listen on all networks?

**Comment by sebastienwarin** [comment]
Fix in release 1.5
