### ISSUE TITLE
Out of memory error on Windows 10, memory leak?

### ISSUE THREAD

**Issue by otlie** [StreamWhatYouHear/SWYH#3]
Detail: System.OutOfMemoryException

NAudio.MediaFoundation.MediaFoundationInterop.MFCreateMemoryBuffer(Int32 cbMaxLength, IMFMediaBuffer& ppBuffer)
vid NAudio.MediaFoundation.MediaFoundationTransform.ReadFromSource()
vid NAudio.MediaFoundation.MediaFoundationTransform.Read(Byte[] buffer, Int32 offset, Int32 count)
vid SWYH.Audio.WaveProviderToWaveStream.Read(Byte[] buffer, Int32 offset, Int32 count)
vid SWYH.Audio.WasapiProvider.waveProcessor()
vid System.Threading.ThreadHelper.ThreadStart_Context(Object state)
vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
vid System.Threading.ThreadHelper.ThreadStart()

I have 16GB, I am not out of memory. Possible leak?

**Comment by sebastienwarin** [comment]
Hum strange, I will test SWYH on Win10 and give you feebacks !

**Comment by sebastienwarin** [comment]
I use SWYH on my Windows 10 without problem ! I can reproduce this bug !

**Comment by kanwakyuudai** [comment]
Hi, I am in a group who are working on handle with issues of this project. Can you provide more details about this issue happened then we can reproduce this situation and see what's going wrong.
