### ISSUE TITLE
Yamaha R-N602 streaming PCM not working.

### ISSUE THREAD

**Issue by bartoszek** [StreamWhatYouHear/SWYH#39]
Although `wav (pcm only up to 192kHz)` is listed in Yamaha:R-N602 [supported dlna stream formats](https://europe.yamaha.com/en/products/audio_visual/hifi_components/r-n602/specs.html) it says `Unable to play` whey trying SWYH with PCM instead of MP3.
WAV streaming works find though on my linux box using [pulseaudio-dlna](https://github.com/masmu/pulseaudio-dlna)
<btw. would be nice to add more stream formats like flac or alac>

**Comment by MX10-AC2N** [comment]
Hi, if you want you can try stream with Localaudiobroadcast or swyh-rs
SWYH is not updated, localaudiobroadcast too, but swyh-rs is under development...

**Comment by bartoszek** [comment]
Thanks for the tip, will check out those.
