### ISSUE TITLE
[Feature Request] option to enable http streaming on startup

### ISSUE THREAD

**Issue by user-4711** [StreamWhatYouHear/SWYH#46]
It would be an awesome addition if http streaming could be automatically enabled on startup.

thanks!

**Comment by MX10-AC2N** [comment]
You should use SWYH-RS instead, the automatic restart function on startup is already there.
https://github.com/dheijl/swyh-rs

**Comment by user-4711** [comment]
Thanks for the info!
And there's a linux version too, great!
Only had a look at the forks, but haven't searched for a rewritten version.

Cheers mate!
