### ISSUE TITLE
Not working with O2 Cloud Speaker: can find device but cannot push audio

### ISSUE THREAD

**Issue by louy2** [StreamWhatYouHear/SWYH#7]
The product: http://www.gizsmart.com/o2-cloud-smart-speaker-voice-control-connect-with-wifi/

The device is listed as available, but when I select it nothing happens. I can push to Foobar just fine. On the other hand, Foobar can push metadata to the device, but not audio. Some other proprietary DLNA implementations are capable of pushing to it.

I wonder how I can further debug this?

**Comment by MichaelJie** [comment]
Hi, I'm in a group to help your problem. But before I start to figure out your problem. I did some research the product website and it seems like it doesn't support any of the stream protocol: DLNA/UPnP, airplay or Google Cast/Chromecast. However, to make this software works it have to support on ULNA/UPnP protocol. And also it seems to be the software requires an external application made by the speaker company. Additionally, by looking at the official website of this product (search http://www.o2fun.com/ ), it says that you also need to download an application on your phone to control it. So, what the suggestion that i want to provide is You should contact with your product support service to have additional support to this problem. If you have any problem please do comment on my post. 
Thank you

**Comment by louy2** [comment]
Thanks. I've since gifted out it so no more need for this ticket.
